FROM mcr.microsoft.com/devcontainers/base:noble
RUN apt-get update
RUN apt-get -y install php php-redis php-soap php-xml php-curl php-opcache php-gd php-sqlite3 php-mysql php-mbstring php-zip composer