name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: curl, dom, gd, mbstring, mysqli, mysqlnd, pdo_mysql, soap, xml, zip
          coverage: none
          tools: composer

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests yfinance

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Environment dependencies
        run: composer run-script --timeout=120 prepare-environment

      - name: Server Up
        run: php -S localhost:8888 -t ./public/ >/tmp/php-server.log 2>&1 &

      - name: Sequential user tests
        run: ./vendor/bin/phpunit --testsuite sequential-user

      - name: Sequential common information exchange traded assets tests
        run: ./vendor/bin/phpunit --testsuite sequential-common-information-exchange-traded-assets

      - name: Tests
        run: ./vendor/bin/phpunit --exclude-testsuite sequential-user,sequential-common-information-exchange-traded-assets
